#include "app_main.h"
#include "lv_port_disp.h"
#include "cluster_app.h"     /* 3-page Colorado cluster + OBD-II poller */
#include "cluster_ui.h"      /* cluster_ui_next_page() for the KEY button */
#include "fdcan_obd.h"       /* g_obd (for the small status screen) */
#include "st7735_status.h"   /* small on-board 0.96" status display */
#include "fdcan.h"           /* hfdcan1 */
#include "lvgl.h"
#include "tim.h"   /* htim1, generated by CubeMX for the backlight PWM */
#include "fault.h"           /* IWDG + last-reset reason */
#include <math.h>
#include <stdbool.h>

#define BACKLIGHT_DUTY_PCT 0u     /* DIAGNOSTIC: 0% at boot -> PA8 held LOW. If backlight still full-on, the MOSFET is not in the backlight current path (wiring). Revert to 100u. */

/* KEY (PC13) gestures: short press = page/step, 3 s hold = toggle backlight mode. */
#define KEY_HOLD_MS     3000u
#define KEY_DEBOUNCE_MS 30u       /* ignore edges closer than this (contact bounce) */
#define BL_STEP_PCT   10u
#define BL_MIN_PCT    10u
#define BL_MAX_PCT    100u

static uint8_t s_bl_pct  = BACKLIGHT_DUTY_PCT;  /* current backlight duty %        */
static uint8_t s_bl_mode = 0;                   /* 0 = pages, 1 = backlight control */
static uint32_t s_key_cnt = 0;                  /* accepted taps (status screen)   */

/* Set TIM1_CH1 (PA8 -> IRF520 gate) duty; clamps to 0..100 %. */
static void backlight_set(uint8_t pct)
{
    if (pct > 100u) pct = 100u;
    s_bl_pct = pct;
    __HAL_TIM_SET_COMPARE(&htim1, TIM_CHANNEL_1,
                          (htim1.Init.Period * pct) / 100u);
}

/* Short tap: next page, or +10% backlight (wrapping) in backlight mode. */
static void key_tap(void)
{
    s_key_cnt++;
    if (s_bl_mode) {
        backlight_set((s_bl_pct >= BL_MAX_PCT) ? BL_MIN_PCT
                                               : (uint8_t)(s_bl_pct + BL_STEP_PCT));
    } else {
        cluster_ui_next_page();
    }
}

/* On-board WeAct LED on PE3 (active low). Display-independent heartbeat:
 *   LED off       -> AppMain_Init never reached (RTOS/boot problem)
 *   LED solid on  -> hung inside AppMain_Init (a display init is blocking)
 *   LED blinking  -> the loop runs */
static void heartbeat_led_init(void)
{
    GPIO_InitTypeDef gi = { 0 };
    __HAL_RCC_GPIOE_CLK_ENABLE();
    gi.Pin = GPIO_PIN_3;
    gi.Mode = GPIO_MODE_OUTPUT_PP;
    gi.Pull = GPIO_NOPULL;
    gi.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOE, &gi);
    HAL_GPIO_WritePin(GPIOE, GPIO_PIN_3, GPIO_PIN_RESET); /* on */
}

/* A press latched by the PC13 EXTI edge. The superloop samples the key once
 * per iteration and an iteration can block ~0.4 s in a full-screen flush, so a
 * tap that started and ended inside one iteration was never seen at all. A
 * rising edge after KEY_DEBOUNCE_MS of quiet latches a press; the closer edges
 * of contact bounce (release bounce included) only restart the quiet window,
 * so they cannot latch a phantom press. */
static volatile uint8_t  s_key_latched;
static volatile uint32_t s_key_press_t;   /* tick of the latched press          */
static volatile uint32_t s_key_edge_t;    /* tick of the last edge of any kind  */

void EXTI15_10_IRQHandler(void)
{
    HAL_GPIO_EXTI_IRQHandler(GPIO_PIN_13);
}

void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
    if (GPIO_Pin != GPIO_PIN_13) return;
    uint32_t now   = HAL_GetTick();
    bool     quiet = (now - s_key_edge_t) >= KEY_DEBOUNCE_MS;
    s_key_edge_t = now;
    if (quiet && HAL_GPIO_ReadPin(GPIOC, GPIO_PIN_13) == GPIO_PIN_SET) {
        s_key_press_t = now;
        s_key_latched = 1;
    }
}

/* On-board WeAct user button "KEY" on PC13. The WeAct examples wire it as an
 * input with a pull-DOWN, so it reads HIGH while pressed. (The board's other
 * two buttons, RESET and BOOT0, can't serve as UI keys.) Short press cycles
 * the cluster page DRIVE -> DIAG -> SNIFF. Both edges raise EXTI15_10 so a
 * press is caught even while the loop is stuck in a display flush. */
static void key_button_init(void)
{
    GPIO_InitTypeDef gi = { 0 };
    __HAL_RCC_GPIOC_CLK_ENABLE();
    gi.Pin = GPIO_PIN_13;
    gi.Mode = GPIO_MODE_IT_RISING_FALLING;
    gi.Pull = GPIO_PULLDOWN;
    gi.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOC, &gi);
    HAL_NVIC_SetPriority(EXTI15_10_IRQn, 10, 0);   /* no RTOS calls in the ISR */
    HAL_NVIC_EnableIRQ(EXTI15_10_IRQn);
}

/* PE3 heartbeat repurposed as a backlight-level indicator: it blinks
 * (backlight% / 10) short pulses, then holds a long gap, and repeats. The
 * ongoing blinking still doubles as the "loop alive" signal. PE3 is active-low
 * (RESET = lit, SET = dark). Non-blocking; call every AppMain_Run iteration. */
static void heartbeat_led_tick(uint32_t t)
{
    enum { LED_ON_MS = 130, LED_OFF_MS = 200, LED_GAP_MS = 1200 };
    static uint32_t at = 0;
    static uint8_t  flashes = 0;    /* ON pulses left in this cycle */
    static uint8_t  lit = 0;        /* current electrical state     */

    if (lit) {                                          /* end of an ON pulse */
        if (t - at >= (uint32_t)LED_ON_MS) {
            HAL_GPIO_WritePin(GPIOE, GPIO_PIN_3, GPIO_PIN_SET);   /* dark */
            lit = 0; at = t;
        }
        return;
    }
    /* dark: short gap between pulses, or the long gap between cycles */
    uint32_t wait = (flashes > 0) ? (uint32_t)LED_OFF_MS : (uint32_t)LED_GAP_MS;
    if (t - at < wait) return;

    if (flashes == 0)                                   /* latch level for a new cycle */
        flashes = (s_bl_pct >= 10u) ? (uint8_t)(s_bl_pct / 10u) : 1u;

    HAL_GPIO_WritePin(GPIOE, GPIO_PIN_3, GPIO_PIN_RESET);        /* lit */
    lit = 1; at = t;
    flashes--;
}

void AppMain_Init(void)
{
    fault_init();           /* latch the reset cause before anything can clear it */
    heartbeat_led_init();   /* first, before anything that might block */
    key_button_init();      /* PC13 page-cycle button */

    lv_port_disp_init();          /* lv_init + the 4" ILI9488 display (default) */
    cluster_app_init(&hfdcan1);   /* build the 3 pages on the 4" + start OBD-II  */
    st7735_status_init();         /* small status screen on SPI4 (2nd display)   */

    /* backlight: TIM1_CH1 / PA8 -> IRF520 gate, per docs/wiring.md */
    HAL_TIM_PWM_Start(&htim1, TIM_CHANNEL_1);
    backlight_set(BACKLIGHT_DUTY_PCT);

    /* Last: the slow display/LVGL bring-up above must not count against it. */
    fault_wdg_start();
}

void AppMain_Run(void)
{
    /* PE3 shows the backlight level as a blink code (also the loop heartbeat) */
    uint32_t t = HAL_GetTick();
    heartbeat_led_tick(t);

    /* KEY (PC13, active-high) gesture state machine:
     *   short press        -> pages mode: next page;  backlight mode: +10% duty
     *   press & hold 3 s   -> toggle pages <-> backlight mode
     * The backlight stepping (visible dimming) is the feedback for the mode. */
    static uint8_t  key_prev = 0;
    static uint32_t key_down_t = 0;
    static uint8_t  key_hold_done = 0;   /* long-press already handled this hold */
    static uint32_t key_last_edge = 0;   /* tick of the last accepted edge (debounce) */
    uint8_t key_now = (HAL_GPIO_ReadPin(GPIOC, GPIO_PIN_13) == GPIO_PIN_SET);

    /* A whole tap between two samples: the level never looked pressed, but
     * the EXTI latched the press. Wait out the debounce window first, so a
     * sample that happened to land on press bounce is not taken as a tap. */
    if (s_key_latched && !key_now && !key_prev &&
        (t - s_key_press_t) >= KEY_DEBOUNCE_MS) {
        s_key_latched = 0;
        key_tap();
    }

    /* Edge-triggered with time-based debounce. A tap fires on the RELEASE edge
     * regardless of how briefly the key was held. Bounce is rejected by
     * ignoring any edge within KEY_DEBOUNCE_MS of the previous accepted one
     * (key_prev is left unchanged so the edge is re-evaluated once the window
     * passes). A press seen here is tracked by level, so its latch is dropped. */
    if (key_now != key_prev && (t - key_last_edge) >= KEY_DEBOUNCE_MS) {
        key_last_edge = t;
        if (key_now) {                                   /* press begins        */
            key_down_t = t;
            key_hold_done = 0;
            s_key_latched = 0;
        } else if (!key_hold_done) {                     /* release -> short tap */
            key_tap();
        }
        key_prev = key_now;
    }
    /* 3 s hold toggles pages <-> backlight mode (uses the live level, not edges) */
    if (key_now && !key_hold_done && (t - key_down_t) >= KEY_HOLD_MS) {
        key_hold_done = 1;                               /* consume this hold   */
        s_bl_mode = !s_bl_mode;                          /* enter/leave mode    */
    }

    lv_timer_handler();   /* LVGL rendering for both displays */
    cluster_app_run();    /* OBD-II: RX drain, request scheduler, UI refresh, watchdog */

    /* refresh the small status screen a few times a second */
    static uint32_t last_status_ms = 0u;
    uint32_t now = lv_tick_get();
    if (now - last_status_ms >= 250u) {
        last_status_ms = now;
        /* NaN means the PID has never answered; casting that to int32_t is UB */
        st7735_status_set(isnan(g_obd.speed) ? 0 : (int32_t)g_obd.speed,
                          isnan(g_obd.rpm)   ? 0 : (int32_t)g_obd.rpm);
        /* KEY diagnostic: page index, live PC13 level, accepted-press count */
        st7735_status_key_dbg(cluster_ui_get_page(), key_now, s_key_cnt);
        /* in brightness mode: overlay the current backlight level on the small screen */
        st7735_status_backlight(s_bl_mode, s_bl_pct);
    }

    /* Only a fully completed iteration (render + OBD + UI) feeds the watchdog,
     * so a hang anywhere in the loop resets the board instead of freezing the
     * last frame on the panel. */
    fault_wdg_kick();
}
