#include "app_main.h"
#include "lv_port_disp.h"
#include "cluster_app.h"     /* 3-page Colorado cluster + OBD-II poller */
#include "cluster_ui.h"      /* cluster_ui_next_page() for the KEY button */
#include "fdcan_obd.h"       /* g_obd (for the small status screen) */
#include "cluster_policy.h"   /* what is fresh enough to show */
#include "st7735_status.h"   /* small on-board 0.96" status display */
#include "fdcan.h"           /* hfdcan1 */
#include "lvgl.h"
#include "tim.h"   /* htim1, generated by CubeMX for the backlight PWM */
#include "fault.h"           /* IWDG + last-reset reason */
#include <math.h>
#include <stdbool.h>

/* Backlight: TIM1_CH1 / PA8 drives the gate of the Si4599's P-channel FET,
 * a high-side switch that conducts while PA8 is LOW (docs/wiring.md). So the
 * PWM is inverted: brightness % = share of the period PA8 is LOW. backlight_set()
 * takes BRIGHTNESS (100 = full), whatever the polarity. Set ACTIVE_LOW to 0 if
 * the gate is ever driven through an inverting stage (an NPN / N-FET pulling
 * the P-FET gate up to 5 V — worth doing: from a 3.3 V pin, with the FET's
 * source on 5 V, "off" is only Vgs = -1.7 V and may not fully close it; to be
 * measured). */
#define BACKLIGHT_ACTIVE_LOW 1
#define BACKLIGHT_BOOT_PCT   100u    /* full brightness at boot (PA8 held LOW, as before) */

/* KEY (PC13) gestures: short press = page/step, 3 s hold = toggle backlight mode. */
#define KEY_HOLD_MS     3000u
#define KEY_DEBOUNCE_MS 30u       /* ignore edges closer than this (contact bounce) */
#define BL_STEP_PCT   10u
#define BL_MIN_PCT    10u
#define BL_MAX_PCT    100u

static uint8_t s_bl_pct  = BACKLIGHT_BOOT_PCT;  /* current brightness %             */
static uint8_t s_bl_mode = 0;                   /* 0 = pages, 1 = backlight control */
static uint32_t s_key_cnt = 0;                  /* accepted taps (status screen)   */

/* Set the backlight BRIGHTNESS, 0..100 %. PWM1 output is high while CNT < CCR,
 * so CCR = (ARR+1) * high% / 100 gives an exact 0 % and 100 % (the old
 * ARR * pct / 100 never reached a steady level at 100 %). */
static void backlight_set(uint8_t pct)
{
    if (pct > 100u) pct = 100u;
    s_bl_pct = pct;
    uint32_t high_pct = BACKLIGHT_ACTIVE_LOW ? (100u - pct) : pct;
    __HAL_TIM_SET_COMPARE(&htim1, TIM_CHANNEL_1,
                          ((htim1.Init.Period + 1u) * high_pct) / 100u);
}

/* Short tap: next page, or +10% backlight (wrapping) in backlight mode. */
static void key_tap(void)
{
    s_key_cnt++;
    if (s_bl_mode) {
        backlight_set((s_bl_pct >= BL_MAX_PCT) ? BL_MIN_PCT
                                               : (uint8_t)(s_bl_pct + BL_STEP_PCT));
    } else {
        cluster_ui_next_page();
    }
}

/* On-board WeAct LED on PE3 (active low). Display-independent heartbeat:
 *   LED off       -> AppMain_Init never reached (RTOS/boot problem)
 *   LED solid on  -> hung inside AppMain_Init (a display init is blocking)
 *   LED blinking  -> the loop runs */
static void heartbeat_led_init(void)
{
    GPIO_InitTypeDef gi = { 0 };
    __HAL_RCC_GPIOE_CLK_ENABLE();
    gi.Pin = GPIO_PIN_3;
    gi.Mode = GPIO_MODE_OUTPUT_PP;
    gi.Pull = GPIO_NOPULL;
    gi.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOE, &gi);
    HAL_GPIO_WritePin(GPIOE, GPIO_PIN_3, GPIO_PIN_RESET); /* on */
}

/* Presses counted by the PC13 EXTI edge. The superloop samples the key once
 * per iteration and an iteration can block ~0.4 s in a full-screen flush, so a
 * tap that started and ended inside one iteration was never seen at all. A
 * rising edge after KEY_DEBOUNCE_MS of quiet counts as a press; the closer
 * edges of contact bounce (release bounce included) only restart the quiet
 * window, so they cannot count a phantom press. The ISR only ever increments
 * s_key_presses and the loop only ever advances its own copy (s_key_seen), so
 * neither side can overwrite the other's update, and several taps inside one
 * iteration stay several taps. */
static volatile uint8_t  s_key_presses;   /* free-running press count (ISR)     */
static volatile uint32_t s_key_press_t;   /* tick of the latest counted press   */
static volatile uint32_t s_key_edge_t;    /* tick of the last edge of any kind  */
static uint8_t           s_key_seen;      /* presses already turned into taps   */

#define KEY_MAX_BURST 4u                  /* cap on taps replayed in one go     */

void EXTI15_10_IRQHandler(void)
{
    HAL_GPIO_EXTI_IRQHandler(GPIO_PIN_13);
}

void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
    if (GPIO_Pin != GPIO_PIN_13) return;
    uint32_t now   = HAL_GetTick();
    bool     quiet = (now - s_key_edge_t) >= KEY_DEBOUNCE_MS;
    s_key_edge_t = now;
    if (quiet && HAL_GPIO_ReadPin(GPIOC, GPIO_PIN_13) == GPIO_PIN_SET) {
        s_key_press_t = now;
        s_key_presses++;
    }
}

/* On-board WeAct user button "KEY" on PC13. The WeAct examples wire it as an
 * input with a pull-DOWN, so it reads HIGH while pressed. (The board's other
 * two buttons, RESET and BOOT0, can't serve as UI keys.) Short press cycles
 * the cluster page DRIVE -> DIAG -> SNIFF. Both edges raise EXTI15_10 so a
 * press is caught even while the loop is stuck in a display flush. */
static void key_button_init(void)
{
    GPIO_InitTypeDef gi = { 0 };
    __HAL_RCC_GPIOC_CLK_ENABLE();
    gi.Pin = GPIO_PIN_13;
    gi.Mode = GPIO_MODE_IT_RISING_FALLING;
    gi.Pull = GPIO_PULLDOWN;
    gi.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOC, &gi);
    HAL_NVIC_SetPriority(EXTI15_10_IRQn, 10, 0);   /* no RTOS calls in the ISR */
    HAL_NVIC_EnableIRQ(EXTI15_10_IRQn);
}

/* PE3 heartbeat repurposed as a backlight-level indicator: it blinks
 * (backlight% / 10) short pulses, then holds a long gap, and repeats. The
 * ongoing blinking still doubles as the "loop alive" signal. PE3 is active-low
 * (RESET = lit, SET = dark). Non-blocking; call every AppMain_Run iteration. */
static void heartbeat_led_tick(uint32_t t)
{
    enum { LED_ON_MS = 130, LED_OFF_MS = 200, LED_GAP_MS = 1200 };
    static uint32_t at = 0;
    static uint8_t  flashes = 0;    /* ON pulses left in this cycle */
    static uint8_t  lit = 0;        /* current electrical state     */

    if (lit) {                                          /* end of an ON pulse */
        if (t - at >= (uint32_t)LED_ON_MS) {
            HAL_GPIO_WritePin(GPIOE, GPIO_PIN_3, GPIO_PIN_SET);   /* dark */
            lit = 0; at = t;
        }
        return;
    }
    /* dark: short gap between pulses, or the long gap between cycles */
    uint32_t wait = (flashes > 0) ? (uint32_t)LED_OFF_MS : (uint32_t)LED_GAP_MS;
    if (t - at < wait) return;

    if (flashes == 0)                                   /* latch level for a new cycle */
        flashes = (s_bl_pct >= 10u) ? (uint8_t)(s_bl_pct / 10u) : 1u;

    HAL_GPIO_WritePin(GPIOE, GPIO_PIN_3, GPIO_PIN_RESET);        /* lit */
    lit = 1; at = t;
    flashes--;
}

void AppMain_Init(void)
{
    heartbeat_led_init();   /* first, before anything that might block */
    key_button_init();      /* PC13 page-cycle button */

    lv_port_disp_init();          /* lv_init + the 4" ILI9488 display (default) */
    cluster_app_init(&hfdcan1);   /* build the 3 pages on the 4" + start OBD-II  */
    st7735_status_init();         /* small status screen on SPI4 (2nd display)   */

    /* backlight: TIM1_CH1 / PA8 -> Si4599 P-FET gate, per docs/wiring.md */
    HAL_TIM_PWM_Start(&htim1, TIM_CHANNEL_1);
    backlight_set(BACKLIGHT_BOOT_PCT);

    /* Init is done: from here the watchdog must be fed every iteration
     * (started with the long boot timeout in main.c). */
    fault_wdg_run_mode();
}

/* Longest superloop period (start to start, including the 5 ms osDelay) over
 * the last full second, shown on DIAG. Wall-clock is right here: it measures
 * how long the loop stalls, which is exactly what the display path costs. */
static uint32_t s_loop_max_ms;

uint32_t app_loop_max_ms(void) { return s_loop_max_ms; }

static void loop_time_tick(uint32_t t)
{
    static uint32_t prev, win_start, win_max;
    uint32_t dt = t - prev;
    prev = t;
    if (dt > win_max) win_max = dt;
    if (t - win_start >= 1000u) {
        s_loop_max_ms = win_max;
        win_max = 0;
        win_start = t;
    }
}

void AppMain_Run(void)
{
    /* PE3 shows the backlight level as a blink code (also the loop heartbeat) */
    uint32_t t = HAL_GetTick();
    loop_time_tick(t);
    heartbeat_led_tick(t);

    /* KEY (PC13, active-high) gesture state machine:
     *   short press        -> pages mode: next page;  backlight mode: +10% duty
     *   press & hold 3 s   -> toggle pages <-> backlight mode
     * The backlight stepping (visible dimming) is the feedback for the mode. */
    static uint8_t  key_prev = 0;
    static uint32_t key_down_t = 0;
    static uint8_t  key_hold_done = 0;   /* long-press already handled this hold */
    static uint32_t key_last_edge = 0;   /* tick of the last accepted edge (debounce) */
    uint8_t key_now = (HAL_GPIO_ReadPin(GPIOC, GPIO_PIN_13) == GPIO_PIN_SET);

    /* Presses the EXTI counted that this loop has not handled yet. */
    uint8_t presses = s_key_presses;
    uint8_t unseen  = (uint8_t)(presses - s_key_seen);
    if (unseen > KEY_MAX_BURST) unseen = KEY_MAX_BURST;

    /* Whole taps between two samples: the level never looked pressed, but the
     * EXTI counted the presses. Wait out the debounce window after the latest
     * one, so a sample that landed on press bounce is not taken as a release. */
    if (unseen && !key_now && !key_prev && (t - s_key_press_t) >= KEY_DEBOUNCE_MS) {
        while (unseen--) key_tap();
        s_key_seen = presses;
    }

    /* Edge-triggered with time-based debounce. A tap fires on the RELEASE edge
     * regardless of how briefly the key was held. Bounce is rejected by
     * ignoring any edge within KEY_DEBOUNCE_MS of the previous accepted one
     * (key_prev is left unchanged so the edge is re-evaluated once the window
     * passes). A press seen here by level is the newest counted press; any
     * counted before it were whole taps inside the stalled iteration. */
    if (key_now != key_prev && (t - key_last_edge) >= KEY_DEBOUNCE_MS) {
        key_last_edge = t;
        if (key_now) {                                   /* press begins        */
            while (unseen-- > 1u) key_tap();
            s_key_seen = presses;
            key_down_t = t;
            key_hold_done = 0;
        } else if (!key_hold_done) {                     /* release -> short tap */
            key_tap();
        }
        key_prev = key_now;
    }
    /* 3 s hold toggles pages <-> backlight mode (uses the live level, not edges) */
    if (key_now && !key_hold_done && (t - key_down_t) >= KEY_HOLD_MS) {
        key_hold_done = 1;                               /* consume this hold   */
        s_bl_mode = !s_bl_mode;                          /* enter/leave mode    */
    }
#if FAULT_TEST
    /* Bench check of the watchdog / fault record (fault.h). */
    if (key_now && (t - key_down_t) >= FAULT_TEST_HOLD_MS) fault_selftest();
#endif

    lv_port_disp_service();   /* repaint / re-init the 4" panel after SPI errors */
    lv_timer_handler();   /* LVGL rendering for both displays */
    cluster_app_run();    /* OBD-II: RX drain, request scheduler, UI refresh, watchdog */

    /* refresh the small status screen a few times a second */
    static uint32_t last_status_ms = 0u;
    uint32_t now = lv_tick_get();
    if (now - last_status_ms >= 250u) {
        last_status_ms = now;
        /* -1 = nothing to show ("--"): never decoded (NaN), stale, or the
         * link is down — the same test as the main display (cluster_policy.h).
         * 0 would be a believable reading, and casting NaN to int is UB. */
        uint32_t tn = HAL_GetTick();
        st_link_t link = !g_obd.can_ok ? ST_LINK_DOWN
                       : (policy_ecm_fresh(&g_obd, tn) ? ST_LINK_ECM : ST_LINK_BUS);
        st7735_status_set(policy_shown(&g_obd, M_SPEED, tn)   ? (int32_t)g_obd.speed : -1,
                          policy_shown(&g_obd, M_RPM, tn)     ? (int32_t)g_obd.rpm   : -1,
                          policy_shown(&g_obd, M_BATTERY, tn) ? (int32_t)(g_obd.battery * 10.0f + 0.5f) : -1,
                          link);
        /* KEY diagnostic: page index, live PC13 level, accepted-press count */
        st7735_status_key_dbg(cluster_ui_get_page(), key_now, s_key_cnt);
        /* in brightness mode: overlay the current backlight level on the small screen */
        st7735_status_backlight(s_bl_mode, s_bl_pct);
    }

    /* Only a fully completed iteration (render + OBD + UI) feeds the watchdog,
     * so a hang anywhere in the loop resets the board instead of freezing the
     * last frame on the panel. */
    fault_wdg_kick();
}
