#include "app_main.h"
#include "lv_port_disp.h"
#include "cluster_app.h"     /* 3-page Colorado cluster + OBD-II poller */
#include "cluster_ui.h"      /* cluster_ui_next_page() for the KEY button */
#include "fdcan_obd.h"       /* g_obd (for the small status screen) */
#include "st7735_status.h"   /* small on-board 0.96" status display */
#include "fdcan.h"           /* hfdcan1 */
#include "lvgl.h"
#include "tim.h"   /* htim1, generated by CubeMX for the backlight PWM */

#define BACKLIGHT_DUTY_PCT 100u   /* full brightness — 80% read as dim on the ILI9488 */

/* On-board WeAct LED on PE3 (active low). Display-independent heartbeat:
 *   LED off       -> AppMain_Init never reached (RTOS/boot problem)
 *   LED solid on  -> hung inside AppMain_Init (a display init is blocking)
 *   LED blinking  -> the loop runs */
static void heartbeat_led_init(void)
{
    GPIO_InitTypeDef gi = { 0 };
    __HAL_RCC_GPIOE_CLK_ENABLE();
    gi.Pin = GPIO_PIN_3;
    gi.Mode = GPIO_MODE_OUTPUT_PP;
    gi.Pull = GPIO_NOPULL;
    gi.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOE, &gi);
    HAL_GPIO_WritePin(GPIOE, GPIO_PIN_3, GPIO_PIN_RESET); /* on */
}

/* On-board WeAct user button "KEY" on PC13. The WeAct examples wire it as an
 * input with a pull-DOWN, so it reads HIGH while pressed. (The board's other
 * two buttons, RESET and BOOT0, can't serve as UI keys.) Short press cycles
 * the cluster page DRIVE -> DPF -> DIAG. */
static void key_button_init(void)
{
    GPIO_InitTypeDef gi = { 0 };
    __HAL_RCC_GPIOC_CLK_ENABLE();
    gi.Pin = GPIO_PIN_13;
    gi.Mode = GPIO_MODE_INPUT;
    gi.Pull = GPIO_PULLDOWN;
    gi.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOC, &gi);
}

void AppMain_Init(void)
{
    heartbeat_led_init();   /* first, before anything that might block */
    key_button_init();      /* PC13 page-cycle button */

    lv_port_disp_init();          /* lv_init + the 4" ILI9488 display (default) */
    cluster_app_init(&hfdcan1);   /* build the 3 pages on the 4" + start OBD-II  */
    st7735_status_init();         /* small status screen on SPI4 (2nd display)   */

    /* backlight: TIM1_CH1 / PA8 -> IRF520 gate, per docs/wiring.md */
    HAL_TIM_PWM_Start(&htim1, TIM_CHANNEL_1);
    __HAL_TIM_SET_COMPARE(&htim1, TIM_CHANNEL_1,
                          (htim1.Init.Period * BACKLIGHT_DUTY_PCT) / 100u);
}

void AppMain_Run(void)
{
    /* heartbeat: independent of both displays, uses the HAL timebase (TIM6) */
    static uint32_t last_led = 0u;
    uint32_t t = HAL_GetTick();
    if (t - last_led >= 1000u) {
        last_led = t;
        HAL_GPIO_TogglePin(GPIOE, GPIO_PIN_3);
    }

    /* KEY (PC13, active-high): on a fresh press, advance the cluster page.
     * 200 ms edge lockout debounces the contact. */
    static uint8_t key_prev = 0;
    static uint32_t key_t = 0;
    static uint32_t key_cnt = 0;
    uint8_t key_now = (HAL_GPIO_ReadPin(GPIOC, GPIO_PIN_13) == GPIO_PIN_SET);
    if (key_now && !key_prev && (t - key_t) > 200u) {
        key_t = t;
        key_cnt++;
        cluster_ui_next_page();
    }
    key_prev = key_now;

    lv_timer_handler();   /* LVGL rendering for both displays */
    cluster_app_run();    /* OBD-II: RX drain, request scheduler, UI refresh, watchdog */

    /* refresh the small status screen a few times a second */
    static uint32_t last_status_ms = 0u;
    uint32_t now = lv_tick_get();
    if (now - last_status_ms >= 250u) {
        last_status_ms = now;
        st7735_status_set((int32_t)g_obd.speed, (int32_t)g_obd.rpm);
        /* KEY diagnostic: page index, live PC13 level, accepted-press count */
        st7735_status_key_dbg(cluster_ui_get_page(), key_now, key_cnt);
    }
}
