/* LVGL 9 <-> ILI9488 (4-wire SPI) display port.
 *
 * This panel has its own GRAM (unlike the dumb RGB panel originally
 * planned), so unlike the LTDC approach, STM32-side memory is not a
 * concern -- LVGL's small partial draw buffers are all that's needed.
 *
 * ILI9488 over 4-wire SPI only supports an 18bpp (3 bytes/pixel, 6
 * significant bits each) pixel format -- there is no 16bpp SPI mode on this
 * controller (that's parallel-interface-only). So every flush expands
 * LVGL's RGB565 buffer into 3-byte RGB666 on the fly, row by row, via
 * row_scratch. This roughly matches the wire format the panel expects; the
 * top 6 bits of each channel come across cleanly, the bottom bits are a
 * standard bit-replication upscale (5->8 / 6->8), not a hardware truncation.
 */

#include "lv_port_disp.h"
#include "lvgl.h"
#include "spi.h"       /* hspi2, generated by CubeMX for the SPI2 peripheral */
#include "cmsis_os2.h" /* osKernelGetTickCount for LVGL's tick source */

#define LCD_CS_PORT   GPIOC
#define LCD_CS_PIN    GPIO_PIN_0
#define LCD_DC_PORT   GPIOC
#define LCD_DC_PIN    GPIO_PIN_4
#define LCD_RST_PORT  GPIOC
#define LCD_RST_PIN   GPIO_PIN_5

#define DISP_BUF_LINES 40u  /* partial buffer height; tune for RAM/perf tradeoff */

static lv_color_t buf1[LCD_H_RES * DISP_BUF_LINES];
static lv_color_t buf2[LCD_H_RES * DISP_BUF_LINES];
static uint8_t row_scratch[LCD_H_RES * 3];  /* one converted RGB666 row at a time */

static inline void cs_low(void)  { HAL_GPIO_WritePin(LCD_CS_PORT, LCD_CS_PIN, GPIO_PIN_RESET); }
static inline void cs_high(void) { HAL_GPIO_WritePin(LCD_CS_PORT, LCD_CS_PIN, GPIO_PIN_SET); }
static inline void dc_cmd(void)  { HAL_GPIO_WritePin(LCD_DC_PORT, LCD_DC_PIN, GPIO_PIN_RESET); }
static inline void dc_data(void) { HAL_GPIO_WritePin(LCD_DC_PORT, LCD_DC_PIN, GPIO_PIN_SET); }

static void lcd_write_cmd(uint8_t cmd)
{
    dc_cmd();
    cs_low();
    HAL_SPI_Transmit(&hspi2, &cmd, 1, HAL_MAX_DELAY);
    cs_high();
}

static void lcd_write_data(const uint8_t *data, uint16_t len)
{
    dc_data();
    cs_low();
    HAL_SPI_Transmit(&hspi2, (uint8_t *)data, len, HAL_MAX_DELAY);
    cs_high();
}

static void lcd_write_data_byte(uint8_t b)
{
    lcd_write_data(&b, 1);
}

static void lcd_set_window(uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2)
{
    uint8_t buf[4];

    lcd_write_cmd(0x2A); /* CASET: column address set */
    buf[0] = (uint8_t)(x1 >> 8); buf[1] = (uint8_t)x1;
    buf[2] = (uint8_t)(x2 >> 8); buf[3] = (uint8_t)x2;
    lcd_write_data(buf, 4);

    lcd_write_cmd(0x2B); /* PASET: page (row) address set */
    buf[0] = (uint8_t)(y1 >> 8); buf[1] = (uint8_t)y1;
    buf[2] = (uint8_t)(y2 >> 8); buf[3] = (uint8_t)y2;
    lcd_write_data(buf, 4);

    lcd_write_cmd(0x2C); /* RAMWR: memory write follows */
}

static void ili9488_init_sequence(void)
{
    HAL_GPIO_WritePin(LCD_RST_PORT, LCD_RST_PIN, GPIO_PIN_RESET);
    HAL_Delay(20);
    HAL_GPIO_WritePin(LCD_RST_PORT, LCD_RST_PIN, GPIO_PIN_SET);
    HAL_Delay(120);

    lcd_write_cmd(0x01); /* software reset */
    HAL_Delay(120);

    /* Full ILI9488 SPI init. The minimal "COLMOD + sleep out + display on"
     * sequence leaves the panel white on most ILI9488 modules -- it needs the
     * power/VCOM/gamma setup below to actually drive the glass. */

    lcd_write_cmd(0xE0); /* positive gamma */
    lcd_write_data((const uint8_t[]){0x00,0x03,0x09,0x08,0x16,0x0A,0x3F,0x78,
                                     0x4C,0x09,0x0A,0x08,0x16,0x1A,0x0F}, 15);
    lcd_write_cmd(0xE1); /* negative gamma */
    lcd_write_data((const uint8_t[]){0x00,0x16,0x19,0x03,0x0F,0x05,0x32,0x45,
                                     0x46,0x04,0x0E,0x0D,0x35,0x37,0x0F}, 15);

    lcd_write_cmd(0xC0); /* power control 1 */
    lcd_write_data((const uint8_t[]){0x17,0x15}, 2);
    lcd_write_cmd(0xC1); /* power control 2 */
    lcd_write_data_byte(0x41);
    lcd_write_cmd(0xC5); /* VCOM control */
    lcd_write_data((const uint8_t[]){0x00,0x12,0x80}, 3);

    lcd_write_cmd(0x36); /* MADCTL: memory access order / orientation */
    lcd_write_data_byte(0x48); /* portrait 320x480 (MX + BGR); flip to 0x88 if upside down */

    lcd_write_cmd(0x3A); /* COLMOD: pixel format */
    lcd_write_data_byte(0x66); /* 18bpp -- the only format ILI9488 supports over 4-wire SPI */

    lcd_write_cmd(0xB0); /* interface mode control */
    lcd_write_data_byte(0x00);
    lcd_write_cmd(0xB1); /* frame rate control */
    lcd_write_data_byte(0xA0);
    lcd_write_cmd(0xB4); /* display inversion control */
    lcd_write_data_byte(0x02);
    lcd_write_cmd(0xB6); /* display function control */
    lcd_write_data((const uint8_t[]){0x02,0x02,0x3B}, 3);
    lcd_write_cmd(0xB7); /* entry mode set */
    lcd_write_data_byte(0xC6);
    lcd_write_cmd(0xF7); /* adjust control 3 */
    lcd_write_data((const uint8_t[]){0xA9,0x51,0x2C,0x82}, 4);

    lcd_write_cmd(0x11); /* sleep out */
    HAL_Delay(120);

    lcd_write_cmd(0x29); /* display on */
    HAL_Delay(20);
}

static void disp_flush_cb(lv_display_t *disp, const lv_area_t *area, uint8_t *px_map)
{
    uint32_t w = (uint32_t)lv_area_get_width(area);
    uint32_t h = (uint32_t)lv_area_get_height(area);

    lcd_set_window((uint16_t)area->x1, (uint16_t)area->y1,
                    (uint16_t)area->x2, (uint16_t)area->y2);

    dc_data();
    cs_low();

    const uint16_t *src = (const uint16_t *)px_map;
    for (uint32_t row = 0; row < h; row++) {
        uint8_t *dst = row_scratch;
        for (uint32_t col = 0; col < w; col++) {
            uint16_t px = *src++;
            uint8_t r5 = (uint8_t)((px >> 11) & 0x1F);
            uint8_t g6 = (uint8_t)((px >> 5) & 0x3F);
            uint8_t b5 = (uint8_t)(px & 0x1F);
            *dst++ = (uint8_t)((r5 << 3) | (r5 >> 2)); /* 5->8 bit replication */
            *dst++ = (uint8_t)((g6 << 2) | (g6 >> 4)); /* 6->8 bit replication */
            *dst++ = (uint8_t)((b5 << 3) | (b5 >> 2));
        }
        HAL_SPI_Transmit(&hspi2, row_scratch, (uint16_t)(w * 3), HAL_MAX_DELAY);
    }

    cs_high();
    lv_display_flush_ready(disp);
}

void lv_port_disp_init(void)
{
    lv_init();
    /* LVGL 9 has no LV_TICK_CUSTOM config anymore -- the tick source is
     * registered at runtime. CMSIS-RTOS2 tick is 1 kHz, i.e. 1 tick = 1 ms,
     * which is exactly what LVGL expects. */
    lv_tick_set_cb(osKernelGetTickCount);

    ili9488_init_sequence();

    lv_display_t *disp = lv_display_create(LCD_H_RES, LCD_V_RES);
    lv_display_set_color_format(disp, LV_COLOR_FORMAT_RGB565);
    lv_display_set_flush_cb(disp, disp_flush_cb);
    lv_display_set_buffers(disp, buf1, buf2, sizeof(buf1), LV_DISPLAY_RENDER_MODE_PARTIAL);
}
