/* LVGL 9 <-> ILI9488 (4-wire SPI) display port.
 *
 * This panel has its own GRAM (unlike the dumb RGB panel originally
 * planned), so unlike the LTDC approach, STM32-side memory is not a
 * concern -- LVGL's small partial draw buffers are all that's needed.
 *
 * ILI9488 over 4-wire SPI only supports an 18bpp (3 bytes/pixel, 6
 * significant bits each) pixel format -- there is no 16bpp SPI mode on this
 * controller (that's parallel-interface-only). So every flush expands
 * LVGL's RGB565 buffer into 3-byte RGB666 on the fly, row by row, via
 * row_scratch. This roughly matches the wire format the panel expects; the
 * top 6 bits of each channel come across cleanly, the bottom bits are a
 * standard bit-replication upscale (5->8 / 6->8), not a hardware truncation.
 *
 * Pixel data goes out by DMA (DMA1 Stream0 -> SPI2 TX). The flush callback
 * converts the area into tx_buf, starts the DMA and reports the flush done at
 * once: LVGL then renders the next area, and the superloop carries on with OBD
 * work, while the wire is busy. The next flush waits for the previous DMA
 * before it touches the bus. The whole DMA path (SPI clock, pin speed, DMA
 * stream, IRQs) is set up here rather than in the CubeMX files, so
 * regenerating code from Dash.ioc cannot drop it.
 */

#include "lv_port_disp.h"
#include "lvgl.h"
#include "spi.h"       /* hspi2, generated by CubeMX for the SPI2 peripheral */
#include "cmsis_os2.h" /* osKernelGetTickCount for LVGL's tick source */
#include "fault.h"     /* FAULT_TEST */
#include <stdbool.h>

#define LCD_CS_PORT   GPIOC
#define LCD_CS_PIN    GPIO_PIN_0
#define LCD_DC_PORT   GPIOC
#define LCD_DC_PIN    GPIO_PIN_4
#define LCD_RST_PORT  GPIOC
#define LCD_RST_PIN   GPIO_PIN_5

#define DISP_BUF_LINES 40u  /* partial buffer height; tune for RAM/perf tradeoff */

/* SPI2 kernel clock is 150 MHz (PLL1Q, Dash.ioc): /8 = 18.75 MHz, twice the old
 * /16. /4 (37.5 MHz) is reported to work on ILI9488 with short leads, but the
 * panel sits on ~15 cm jumper wires here; try it only after a clean run at /8. */
#define LCD_SPI_PRESCALER SPI_BAUDRATEPRESCALER_8

/* Render buffers sized in RGB565 bytes. Not lv_color_t[]: in LVGL 9 lv_color_t
 * is 3 bytes whatever the display format, so such an array is 1.5x larger
 * than meant and LVGL (which divides the byte size by the RGB565 stride) hands
 * the flush taller areas than DISP_BUF_LINES. That overran tx_buf and zeroed
 * the HAL handles behind it (htim6 -> tick IRQ storm -> watchdog reset loop). */
#define DISP_BUF_PX    (LCD_H_RES * DISP_BUF_LINES)
static uint8_t buf1[DISP_BUF_PX * 2u] __attribute__((aligned(4)));
static uint8_t buf2[DISP_BUF_PX * 2u] __attribute__((aligned(4)));

/* One converted RGB666 area, the DMA source. In AXI SRAM (.bss, RAM_D1), which
 * DMA1 can reach; DTCM it cannot. Cache-line aligned and sized so cleaning the
 * D-cache over it never touches a neighbour. */
#define TX_BUF_BYTES (((DISP_BUF_PX * 3u) + 31u) & ~31u)
static uint8_t tx_buf[TX_BUF_BYTES] __attribute__((aligned(32)));

static DMA_HandleTypeDef s_dma_tx;
static volatile bool     s_dma_busy;   /* set at DMA start, cleared in the TX-complete IRQ */

static inline void cs_low(void)  { HAL_GPIO_WritePin(LCD_CS_PORT, LCD_CS_PIN, GPIO_PIN_RESET); }
static inline void cs_high(void) { HAL_GPIO_WritePin(LCD_CS_PORT, LCD_CS_PIN, GPIO_PIN_SET); }
static inline void dc_cmd(void)  { HAL_GPIO_WritePin(LCD_DC_PORT, LCD_DC_PIN, GPIO_PIN_RESET); }
static inline void dc_data(void) { HAL_GPIO_WritePin(LCD_DC_PORT, LCD_DC_PIN, GPIO_PIN_SET); }

/* SPI transfers that went wrong: a blocking send that timed out or failed, a
 * refused DMA start, a DMA error, a DMA transfer abandoned by dma_wait(), or
 * an area too big for tx_buf. Shown on DIAG when non-zero.
 * Bounded timeouts instead of HAL_MAX_DELAY: a stuck SPI used to hang the
 * loop until the IWDG reset the board; now the transfer is aborted, counted,
 * and the next repaint tries again. */
#define LCD_CMD_TIMEOUT_MS   10u    /* commands / parameters: a few bytes          */
#define LCD_BULK_TIMEOUT_MS 100u    /* a full area: ~17 ms at 18.75 MHz            */
static volatile uint16_t s_spi_err;

/* Recovery. A lost area is not a finished repaint: flush_ready() has to be
 * called anyway (LVGL would wait forever), but the panel's GRAM keeps the old
 * pixels there until that widget happens to change. And a run of errors with
 * no good transfer in between may mean the panel or the SPI block lost its
 * state. lv_port_disp_service() repairs both from the loop:
 *   - after any error: repaint the whole screen, at most every
 *     LCD_REPAINT_GAP_MS (a full repaint is ~200 ms of wire time);
 *   - after LCD_RECOVER_STREAK errors in a row: reset and re-init the panel
 *     first (~400 ms, well inside the 3 s IWDG), at most every
 *     LCD_RECOVER_GAP_MS, counted (R on DIAG).
 * A panel that resets itself (supply dip) produces no SPI error on this
 * write-only bus and is not detected here. */
#define LCD_RECOVER_STREAK    3u
#define LCD_REPAINT_GAP_MS 1000u
#define LCD_RECOVER_GAP_MS 5000u
static volatile uint16_t s_err_streak;     /* errors since the last good DMA area */
static volatile bool     s_need_repaint;   /* something did not reach the panel   */
static uint16_t          s_recover_cnt;
static lv_display_t     *s_disp;

uint16_t lv_port_disp_spi_errors(void) { return s_spi_err; }
uint16_t lv_port_disp_recoveries(void) { return s_recover_cnt; }

static void spi_err(void)
{
    if (s_spi_err < 0xFFFFu) s_spi_err++;
    if (s_err_streak < 0xFFFFu) s_err_streak++;
    s_need_repaint = true;
}

static void lcd_tx(const uint8_t *p, uint16_t len, uint32_t timeout_ms)
{
    if (HAL_SPI_Transmit(&hspi2, (uint8_t *)p, len, timeout_ms) != HAL_OK) {
        HAL_SPI_Abort(&hspi2);
        spi_err();
    }
}

static void lcd_write_cmd(uint8_t cmd)
{
    dc_cmd();
    cs_low();
    lcd_tx(&cmd, 1, LCD_CMD_TIMEOUT_MS);
    cs_high();
}

static void lcd_write_data(const uint8_t *data, uint16_t len)
{
    dc_data();
    cs_low();
    lcd_tx(data, len, LCD_CMD_TIMEOUT_MS);
    cs_high();
}

static void lcd_write_data_byte(uint8_t b)
{
    lcd_write_data(&b, 1);
}

static void lcd_set_window(uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2)
{
    uint8_t buf[4];

    lcd_write_cmd(0x2A); /* CASET: column address set */
    buf[0] = (uint8_t)(x1 >> 8); buf[1] = (uint8_t)x1;
    buf[2] = (uint8_t)(x2 >> 8); buf[3] = (uint8_t)x2;
    lcd_write_data(buf, 4);

    lcd_write_cmd(0x2B); /* PASET: page (row) address set */
    buf[0] = (uint8_t)(y1 >> 8); buf[1] = (uint8_t)y1;
    buf[2] = (uint8_t)(y2 >> 8); buf[3] = (uint8_t)y2;
    lcd_write_data(buf, 4);

    lcd_write_cmd(0x2C); /* RAMWR: memory write follows */
}

static void ili9488_init_sequence(void)
{
    HAL_GPIO_WritePin(LCD_RST_PORT, LCD_RST_PIN, GPIO_PIN_RESET);
    HAL_Delay(20);
    HAL_GPIO_WritePin(LCD_RST_PORT, LCD_RST_PIN, GPIO_PIN_SET);
    HAL_Delay(120);

    lcd_write_cmd(0x01); /* software reset */
    HAL_Delay(120);

    /* Full ILI9488 SPI init. The minimal "COLMOD + sleep out + display on"
     * sequence leaves the panel white on most ILI9488 modules -- it needs the
     * power/VCOM/gamma setup below to actually drive the glass. */

    lcd_write_cmd(0xE0); /* positive gamma */
    lcd_write_data((const uint8_t[]){0x00,0x03,0x09,0x08,0x16,0x0A,0x3F,0x78,
                                     0x4C,0x09,0x0A,0x08,0x16,0x1A,0x0F}, 15);
    lcd_write_cmd(0xE1); /* negative gamma */
    lcd_write_data((const uint8_t[]){0x00,0x16,0x19,0x03,0x0F,0x05,0x32,0x45,
                                     0x46,0x04,0x0E,0x0D,0x35,0x37,0x0F}, 15);

    lcd_write_cmd(0xC0); /* power control 1 */
    lcd_write_data((const uint8_t[]){0x17,0x15}, 2);
    lcd_write_cmd(0xC1); /* power control 2 */
    lcd_write_data_byte(0x41);
    lcd_write_cmd(0xC5); /* VCOM control — raised VCM (0x12->0x24) to deepen
                          * black / cut the milky glow on this panel. Tune this
                          * one byte: higher = deeper black up to a point, then
                          * it starts to flicker; lower = washed out again. */
    lcd_write_data((const uint8_t[]){0x00,0x1E,0x80}, 3);

    lcd_write_cmd(0x36); /* MADCTL: memory access order / orientation */
    lcd_write_data_byte(0x48); /* portrait 320x480 (MX + BGR); flip to 0x88 if upside down */

    lcd_write_cmd(0x3A); /* COLMOD: pixel format */
    lcd_write_data_byte(0x66); /* 18bpp -- the only format ILI9488 supports over 4-wire SPI */

    lcd_write_cmd(0xB0); /* interface mode control */
    lcd_write_data_byte(0x00);
    lcd_write_cmd(0xB1); /* frame rate control */
    lcd_write_data_byte(0xA0);
    lcd_write_cmd(0xB4); /* display inversion control */
    lcd_write_data_byte(0x02);
    lcd_write_cmd(0xB6); /* display function control */
    lcd_write_data((const uint8_t[]){0x02,0x02,0x3B}, 3);
    lcd_write_cmd(0xB7); /* entry mode set */
    lcd_write_data_byte(0xC6);
    lcd_write_cmd(0xF7); /* adjust control 3 */
    lcd_write_data((const uint8_t[]){0xA9,0x51,0x2C,0x82}, 4);

    lcd_write_cmd(0x11); /* sleep out */
    HAL_Delay(120);

    lcd_write_cmd(0x29); /* display on */
    HAL_Delay(20);
}

/* Wait for the previous area's DMA. Bounded so a DMA that never completes
 * cannot hang the loop silently: the transfer is abandoned and the IWDG keeps
 * running as usual. The longest legal transfer (TX_BUF_BYTES at 18.75 MHz) is
 * ~17 ms; this gives it 100 ms. */
static void dma_wait(void)
{
    uint32_t t0 = HAL_GetTick();
    while (s_dma_busy) {
        if (HAL_GetTick() - t0 > 100u) {
            HAL_SPI_Abort(&hspi2);
            cs_high();
            s_dma_busy = false;
            spi_err();
            break;
        }
    }
}

void HAL_SPI_TxCpltCallback(SPI_HandleTypeDef *hspi)
{
    if (hspi == &hspi2) {
        cs_high();
        s_dma_busy = false;
        s_err_streak = 0;            /* a whole area made it: the link works */
    }
}

void HAL_SPI_ErrorCallback(SPI_HandleTypeDef *hspi)
{
    if (hspi == &hspi2) {
        cs_high();
        s_dma_busy = false;
        spi_err();                   /* the area did not reach the panel */
    }
}

void DMA1_Stream0_IRQHandler(void) { HAL_DMA_IRQHandler(&s_dma_tx); }
void SPI2_IRQHandler(void)         { HAL_SPI_IRQHandler(&hspi2); }

static void disp_flush_cb(lv_display_t *disp, const lv_area_t *area, uint8_t *px_map)
{
    uint32_t w = (uint32_t)lv_area_get_width(area);
    uint32_t h = (uint32_t)lv_area_get_height(area);
    uint32_t n = w * h * 3u;

    /* tx_buf may still be on the wire from the previous area. */
    dma_wait();

    /* Never write past tx_buf. Cannot happen with the buffers above; if it
     * ever does, drop the area rather than corrupt memory (a missing patch
     * repaints on the next change, a smashed HAL handle resets the board). */
    if (n > TX_BUF_BYTES) {
        spi_err();                   /* counted: a dropped area is a lost repaint */
        lv_display_flush_ready(disp);
        return;
    }

    const uint16_t *src = (const uint16_t *)px_map;
    uint8_t *dst = tx_buf;
    for (uint32_t i = 0; i < w * h; i++) {
        uint16_t px = *src++;
        uint8_t r5 = (uint8_t)((px >> 11) & 0x1F);
        uint8_t g6 = (uint8_t)((px >> 5) & 0x3F);
        uint8_t b5 = (uint8_t)(px & 0x1F);
        *dst++ = (uint8_t)((r5 << 3) | (r5 >> 2)); /* 5->8 bit replication */
        *dst++ = (uint8_t)((g6 << 2) | (g6 >> 4)); /* 6->8 bit replication */
        *dst++ = (uint8_t)((b5 << 3) | (b5 >> 2));
    }
    /* The DMA reads RAM, not the D-cache. */
    SCB_CleanDCache_by_Addr((uint32_t *)tx_buf, (int32_t)((n + 31u) & ~31u));

    uint16_t e0 = s_spi_err;
    lcd_set_window((uint16_t)area->x1, (uint16_t)area->y1,
                    (uint16_t)area->x2, (uint16_t)area->y2);
    if (s_spi_err != e0) {
        /* The window did not land: the pixels would be written wherever the
         * panel's address pointer happens to be. Drop the area; the service
         * repaints it. */
        lv_display_flush_ready(disp);
        return;
    }
    dc_data();
    cs_low();
    s_dma_busy = true;
    if (HAL_SPI_Transmit_DMA(&hspi2, tx_buf, (uint16_t)n) != HAL_OK) {
        /* Fall back to a blocking send so the frame is not lost; the refused
         * DMA start is counted either way. */
        s_dma_busy = false;
        spi_err();
        lcd_tx(tx_buf, (uint16_t)n, LCD_BULK_TIMEOUT_MS);
        cs_high();
    }

    /* px_map has been copied out, so LVGL may render into it again. */
    lv_display_flush_ready(disp);
}

/* SPI2 speed-up and DMA. Runs once, before the panel init sequence. */
static void spi2_dma_init(void)
{
    /* Re-init SPI2 with everything this panel depends on, not only the faster
     * clock, so a CubeMX regen of spi.c cannot change it behind our back.
     * Dash.ioc matches mode 0 and /16 but keeps 2LINES (switching it to
     * half-duplex in CubeMX would also drop the MISO pin); this block is what
     * guarantees the panel's settings. Mode 0 because these ILI9488 clones
     * want it; 1LINE because the panel is write-only. */
    hspi2.Init.Mode              = SPI_MODE_MASTER;
    hspi2.Init.Direction         = SPI_DIRECTION_1LINE;
    hspi2.Init.DataSize          = SPI_DATASIZE_8BIT;
    hspi2.Init.CLKPolarity       = SPI_POLARITY_LOW;
    hspi2.Init.CLKPhase          = SPI_PHASE_1EDGE;
    hspi2.Init.NSS               = SPI_NSS_SOFT;
    hspi2.Init.FirstBit          = SPI_FIRSTBIT_MSB;
    hspi2.Init.BaudRatePrescaler = LCD_SPI_PRESCALER;
    if (HAL_SPI_Init(&hspi2) != HAL_OK) Error_Handler();

    /* The CubeMX pin config is GPIO_SPEED_FREQ_LOW (~12 MHz); too slow an edge
     * for 18.75 MHz. HIGH, not VERY_HIGH: less ringing on long jumper wires. */
    GPIO_InitTypeDef gi = { 0 };
    gi.Pin       = GPIO_PIN_13 | GPIO_PIN_14 | GPIO_PIN_15;
    gi.Mode      = GPIO_MODE_AF_PP;
    gi.Pull      = GPIO_NOPULL;
    gi.Speed     = GPIO_SPEED_FREQ_HIGH;
    gi.Alternate = GPIO_AF5_SPI2;
    HAL_GPIO_Init(GPIOB, &gi);

    __HAL_RCC_DMA1_CLK_ENABLE();
    s_dma_tx.Instance                 = DMA1_Stream0;
    s_dma_tx.Init.Request             = DMA_REQUEST_SPI2_TX;
    s_dma_tx.Init.Direction           = DMA_MEMORY_TO_PERIPH;
    s_dma_tx.Init.PeriphInc           = DMA_PINC_DISABLE;
    s_dma_tx.Init.MemInc              = DMA_MINC_ENABLE;
    s_dma_tx.Init.PeriphDataAlignment = DMA_PDATAALIGN_BYTE;
    s_dma_tx.Init.MemDataAlignment    = DMA_MDATAALIGN_BYTE;
    s_dma_tx.Init.Mode                = DMA_NORMAL;
    s_dma_tx.Init.Priority            = DMA_PRIORITY_LOW;
    s_dma_tx.Init.FIFOMode            = DMA_FIFOMODE_DISABLE;
    if (HAL_DMA_Init(&s_dma_tx) != HAL_OK) Error_Handler();
    __HAL_LINKDMA(&hspi2, hdmatx, s_dma_tx);

    /* Priority 6: below configMAX_SYSCALL_INTERRUPT_PRIORITY (5); the handlers
     * make no RTOS calls anyway. */
    HAL_NVIC_SetPriority(DMA1_Stream0_IRQn, 6, 0);
    HAL_NVIC_EnableIRQ(DMA1_Stream0_IRQn);
    HAL_NVIC_SetPriority(SPI2_IRQn, 6, 0);
    HAL_NVIC_EnableIRQ(SPI2_IRQn);
}

void lv_port_disp_init(void)
{
    lv_init();
    /* LVGL 9 has no LV_TICK_CUSTOM config anymore -- the tick source is
     * registered at runtime. CMSIS-RTOS2 tick is 1 kHz, i.e. 1 tick = 1 ms,
     * which is exactly what LVGL expects. */
    lv_tick_set_cb(osKernelGetTickCount);

    spi2_dma_init();
    ili9488_init_sequence();

    lv_display_t *disp = lv_display_create(LCD_H_RES, LCD_V_RES);
    lv_display_set_color_format(disp, LV_COLOR_FORMAT_RGB565);
    lv_display_set_flush_cb(disp, disp_flush_cb);
    lv_display_set_buffers(disp, buf1, buf2, sizeof(buf1), LV_DISPLAY_RENDER_MODE_PARTIAL);
    s_disp = disp;
    s_err_streak = 0;               /* init-time errors are covered by the */
                                    /* first full paint                    */
}

#if FAULT_TEST == 3
/* Bench check of the recovery: a run of errors as a broken link would give. */
void lv_port_disp_inject_errors(void)
{
    for (unsigned i = 0; i < LCD_RECOVER_STREAK; i++) spi_err();
}
#endif

void lv_port_disp_service(void)
{
    static uint32_t t_repaint, t_recover;
    static bool     recovered_once;
    if (s_disp == NULL || !s_need_repaint) return;
    uint32_t now = HAL_GetTick();
    if (now - t_repaint < LCD_REPAINT_GAP_MS) return;
    t_repaint = now;

    if (s_err_streak >= LCD_RECOVER_STREAK &&
        (!recovered_once || now - t_recover >= LCD_RECOVER_GAP_MS)) {
        recovered_once = true;
        t_recover = now;
        dma_wait();                  /* nothing of ours left on the wire     */
        HAL_SPI_Abort(&hspi2);
        cs_high();
        ili9488_init_sequence();     /* errors in here count as usual        */
        if (s_recover_cnt < 0xFFFFu) s_recover_cnt++;
        s_err_streak = 0;
    }
    s_need_repaint = false;
    lv_obj_invalidate(lv_display_get_screen_active(s_disp));
}
